ALTER TABLE events ADD COLUMN IF NOT EXISTS card_bg_from  TEXT NOT NULL DEFAULT '#7c3aed';
ALTER TABLE events ADD COLUMN IF NOT EXISTS card_bg_to    TEXT NOT NULL DEFAULT '#1e1b4b';
ALTER TABLE events ADD COLUMN IF NOT EXISTS card_bg_image TEXT;
ALTER TABLE events ADD COLUMN IF NOT EXISTS host_label    TEXT;
